### PR TITLE
Update yottagram-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by dashinfantry** [comment]
I have update Chinese translation totally.

**Comment by Michal-Szczepaniak** [comment]
stop making new pull requests,

**Comment by dashinfantry** [comment]
Soere.It occurred some network errors on my device.
This one is the last version.

**Comment by Michal-Szczepaniak** [comment]
could you update PR? there seem to be some changes that can't merge

**Comment by dashinfantry** [comment]
Reopen

**Pull request closed without merging**
